-- Init schema and user
-- CREATE ROLE "camunda" LOGIN PASSWORD 'changeme';
-- CREATE SCHEMA "camunda";
-- ALTER SCHEMA "camunda" OWNER TO "camunda";
-- ALTER ROLE "camunda"
-- SET search_path TO "camunda";
-- ALTER DEFAULT PRIVILEGES IN SCHEMA "camunda"
-- GRANT ALL ON TABLES TO "camunda";